### ISSUE TITLE
Unable to compile ULAM

### ISSUE THREAD

**Issue by walpolea** [DaveAckley/SPLAT#1]
Per the instructions:
`pushd; make -f rebuild.mk; popd`

Getting multiple compilation errors and then it dies. See images for details.
<img width="1435" alt="screen shot 2018-10-23 at 11 10 54 pm" src="https://user-images.githubusercontent.com/133423/47410017-511fe880-d719-11e8-9c95-cb2bf4225e95.png">

<img width="1427" alt="screen shot 2018-10-23 at 11 11 20 pm" src="https://user-images.githubusercontent.com/133423/47410016-50875200-d719-11e8-9e00-9a5e37572c7c.png">

<img width="1431" alt="screen shot 2018-10-23 at 11 11 39 pm" src="https://user-images.githubusercontent.com/133423/47410014-50875200-d719-11e8-8461-8777a7f20e0b.png">

**Comment by DaveAckley** [comment]
Thanks for the report.  Try pulling to get commit
    0f2c486 HEAD@{0}: commit: Disable implicit fallthrough warnings for now
and see how far the rebuild.mk gets.  There may be a second issue about 
tests.inc, but that may fix itself on a second try.

**Comment by walpolea** [comment]
This worked, thank you! Though I had to figure out some dependencies to install on my fresh virtualized ubuntu 18.10, so it may be worth adding to the readme:

```
#Extra needed dependencies to build

sudo apt-get install build-essential g++
sudo apt-get install libsdl1.2-dev
sudo apt-get install libsdl-image1.2-dev
sudo apt-get install libsdl-ttf2.0-dev
sudo apt-get install libcapture-tiny-perl
sudo apt-get install libcrypt-openssl-rsa-perl

#To create the mfz signing file to run demos

cd ~/REPOS/MFM/bin/
./mfzmake keygen "some name"
./mfzmake default "some name"
```

**Comment by walpolea** [comment]
Also, only FB demo worked, C211 and SwapLine just stalled in make. This might just be because the VM is soooo slow, not sure.


UPDATE:

It's just slow, all demos work.
